import { ParsedFact } from '@prisma/client';

export interface XBRLCompanyMetadata {
  cin: string;
  name: string;
  financialYear: string;
}

export const generateXBRLInstanceDocument = (
  metadata: XBRLCompanyMetadata,
  facts: ParsedFact[]
): string => {
  const fyId = `FY_${metadata.financialYear.replace(/-/g, '_')}_${metadata.cin}`;
  
  // Format period dates
  const yearStart = metadata.financialYear.split('-')[0];
  const yearEnd = '20' + metadata.financialYear.split('-')[1]; // handles "2024-25" -> "2025" or similar
  const formattedStart = `${yearStart}-04-01`;
  const formattedEnd = `${yearEnd}-03-31`;

  let factNodes = '';

  for (const f of facts) {
    const tagName = f.xmlTag || `mca-indas:${f.factKey}`;
    // Strip namespace prefix if it already has one for clean XML generation
    const elementTag = tagName.includes(':') ? tagName : `mca-indas:${tagName}`;
    
    factNodes += `  <${elementTag} contextRef="${fyId}" unitRef="${f.unit}" decimals="0">${f.factValue}</${elementTag}>\n`;
  }

  const xmlContent = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by AI XBRL Studio Compliance Engine -->
<xbrli:xbrl xmlns:mca-indas="http://www.mca.gov.in/XBRL/2024/taxonomy/mca-indas"
            xmlns:xbrli="http://www.xbrl.org/2003/instance"
            xmlns:link="http://www.xbrl.org/2003/linkbase"
            xmlns:xlink="http://www.w3.org/1999/xlink"
            xmlns:iso4217="http://www.xbrl.org/2003/iso4217">
  
  <link:schemaRef xlink:type="simple" xlink:href="http://www.mca.gov.in/XBRL/2024/taxonomy/mca-indas/mca-indas-entry.xsd" />

  <xbrli:context id="${fyId}">
    <xbrli:entity>
      <xbrli:identifier scheme="http://www.mca.gov.in/CIN">${metadata.cin}</xbrli:identifier>
    </xbrli:entity>
    <xbrli:period>
      <xbrli:startDate>${formattedStart}</xbrli:startDate>
      <xbrli:endDate>${formattedEnd}</xbrli:endDate>
    </xbrli:period>
  </xbrli:context>

  <xbrli:unit id="INR">
    <xbrli:measure>iso4217:INR</xbrli:measure>
  </xbrli:unit>

${factNodes}</xbrli:xbrl>
`;

  return xmlContent;
};
